#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/example_demo_6.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/oocsi.jar:$APPDIR/lib/io.jar:$APPDIR/lib/beads.jar:$APPDIR/lib/jarjar-1.0.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/org-jaudiolibs-audioservers-jack.jar:$APPDIR/lib/org-jaudiolibs-audioservers-javasound.jar:$APPDIR/lib/org-jaudiolibs-audioservers.jar:$APPDIR/lib/org-jaudiolibs-jnajack.jar:$APPDIR/lib/tools.jar:$APPDIR/lib/tritonus_aos-0.3.6.jar:$APPDIR/lib/tritonus_share.jar" example_demo_6 "$@"
